<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a435822c-2639-428f-8509-0050a9e26591</elementGuidId>
    <imagePath></imagePath>
    <name>button_TryItOut</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]/div[2]/div[4]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fd-gds-component\ fd-common-card"]:nth-child(4) [class="fd-standard-card--link-btn\ fs-standard-card--url\ fd-common-btn\ fd-primary-btn"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'try out the savings calculator') and equals(@href,'/en/savingscalculator/') and equals(@text,'Try it out')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[title="try out the savings calculator"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/savingscalculator/</value>
        <webElementGuid>63327e27-e6a4-4e9b-af9c-dc7aac5c3b4d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Try it out</value>
        <webElementGuid>63327e27-e6a4-4e9b-af9c-dc7aac5c3b4d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>try out the savings calculator</value>
        <webElementGuid>63327e27-e6a4-4e9b-af9c-dc7aac5c3b4d</webElementGuid>
    </webElementProperties>
</WebElementEntity>