<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0ae125fe-59b9-4785-877c-6edd05ef8a9e</elementGuidId>
    <imagePath></imagePath>
    <name>link_GrowthCalculator</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/growthcalculator/') and equals(@text,'Growth calculator
            
            Find out how much your savings will grow over time by making regular contributions.
            
            Try it out')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/growthcalculator/</value>
        <webElementGuid>0bdbbb3c-549d-47c3-b23f-99a344489dca</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Growth calculator
        
        Find out how much your savings will grow over time by making regular contributions.
        
        Try it out</value>
        <webElementGuid>0bdbbb3c-549d-47c3-b23f-99a344489dca</webElementGuid>
    </webElementProperties>
</WebElementEntity>