<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0d0a4334-d540-4097-9338-a6293628d7b5</elementGuidId>
    <imagePath></imagePath>
    <name>fidelityCanadaSustainabilityLink</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/footer[1]/div[1]/div[1]/div[3]/div[1]/ul[1]/li[1]/ul[1]/li[11]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-child(11) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/aboutus/sustainability/') and equals(@text,'Fidelity Canada Sustainability')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>li:nth-child(11) &gt; a</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/aboutus/sustainability/</value>
        <webElementGuid>50c3fe0c-bf62-4efc-9b57-c3942c7bfedf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Fidelity Canada Sustainability</value>
        <webElementGuid>50c3fe0c-bf62-4efc-9b57-c3942c7bfedf</webElementGuid>
    </webElementProperties>
</WebElementEntity>