<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a0693837-174f-4343-ab72-bc9e4d47b87e</elementGuidId>
    <imagePath></imagePath>
    <name>allFidelityFundsDropdown</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="dropdown\ bootstrap-select\ js-dynamic-table-categories-filter\ fd-\ mb-0\ mr-0\ mb-lg-2\ mr-lg-2\ px-0\ col-auto"] &gt; [type="button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'All Fidelity Funds') and equals(@type,'button') and equals(@text,'All Fidelity Funds')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.dropdown &gt; .btn &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>All Fidelity Funds</value>
        <webElementGuid>50c3fe0c-bf62-4efc-9b57-c3942c7bfedf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>All Fidelity Funds</value>
        <webElementGuid>50c3fe0c-bf62-4efc-9b57-c3942c7bfedf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>50c3fe0c-bf62-4efc-9b57-c3942c7bfedf</webElementGuid>
    </webElementProperties>
</WebElementEntity>