<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7459b1f3-fc43-4fc2-a7b8-1539f2a650e7</elementGuidId>
    <imagePath></imagePath>
    <name>button_AllFidelityFunds</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="dropdown\ bootstrap-select\ js-dynamic-table-categories-filter\ fd-\ mb-0\ mr-0\ mb-lg-2\ mr-lg-2\ px-0\ col-auto"] &gt; [type="button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'All Fidelity Funds') and equals(@type,'button') and equals(@text,'All Fidelity Funds')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=combobox[name="All Fidelity Funds"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>All Fidelity Funds</value>
        <webElementGuid>deef9c7a-44b6-47a4-a2d1-3f7be67def7c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>All Fidelity Funds</value>
        <webElementGuid>deef9c7a-44b6-47a4-a2d1-3f7be67def7c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>deef9c7a-44b6-47a4-a2d1-3f7be67def7c</webElementGuid>
    </webElementProperties>
</WebElementEntity>