<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>25f6977b-a0b1-47c8-93c6-1477a9635dec</elementGuidId>
    <imagePath></imagePath>
    <name>link_bsSelect10</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#bs-select-1-0</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'bs-select-1-0') and equals(@text,'My watch list')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#bs-select-1-0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>bs-select-1-0</value>
        <webElementGuid>7a57bac6-5cf5-4753-9011-30930c1974ce</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>My watch list</value>
        <webElementGuid>7a57bac6-5cf5-4753-9011-30930c1974ce</webElementGuid>
    </webElementProperties>
</WebElementEntity>