<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>83118815-9899-4e7a-bbe7-89ff6359af02</elementGuidId>
    <imagePath></imagePath>
    <name>financialGoalsLink</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[3]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="flex-column\ background-padding\ col-12\ col-lg-4\ \ \ \ \ "]:nth-child(3) [class="fd-standard-card--regular\ fd-standard-card--link\ fd-standard-card--clickable\ fd-standard-manual\ fd-mb-32\ fd-card-row--3"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/accelerate-your-dreams/') and equals(@text,'Keep your financial goals in mind.
            
            They can help you keep in mind the time horizon over which you are investing, and give you a sense of purpose while investing.
            
            How do I stay ahead of all the financial noise?')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Keep your financial goals in"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/accelerate-your-dreams/</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Keep your financial goals in mind.
        
        They can help you keep in mind the time horizon over which you are investing, and give you a sense of purpose while investing.
        
        How do I stay ahead of all the financial noise?</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
</WebElementEntity>