<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fa5a1a97-f522-4c43-b65c-c769f321adda</elementGuidId>
    <imagePath></imagePath>
    <name>link_navigationActions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/main[1]/div[6]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ next-btn\ first-nav"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'javascript:void(0);') and equals(@text,'Next')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#myplanMain &gt;&gt; internal:role=link &gt;&gt; nth=${link_navigationActions_nth}</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>javascript:void(0);</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Next</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
</WebElementEntity>