<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0e141eee-2dcf-4206-b1cd-b78f89a4260c</elementGuidId>
    <imagePath></imagePath>
    <name>link_webcast_for_investors_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="flex-column\ background-padding\ col-12\ col-lg-6\ \ \ \ \ "]:nth-child(1) [class="card-with-links--link\ link-with-href"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'view investor webcasts') and equals(@href,'https://go.fidelity.ca/theupside-express-registration.html') and equals(@text,'The Upside: Webcasts for investors')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="The Upside: Webcasts for"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://go.fidelity.ca/theupside-express-registration.html</value>
        <webElementGuid>86ff7c32-aad1-4b36-b36c-efe219fdf365</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>The Upside: Webcasts for investors</value>
        <webElementGuid>86ff7c32-aad1-4b36-b36c-efe219fdf365</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>view investor webcasts</value>
        <webElementGuid>86ff7c32-aad1-4b36-b36c-efe219fdf365</webElementGuid>
    </webElementProperties>
</WebElementEntity>