<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a755b479-0b7a-45ee-8fab-e7a4ebb054a1</elementGuidId>
    <imagePath></imagePath>
    <name>link_tools_and_calculators</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/div[1]/div[1]/menu[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fd-megamenu--desktop__section\ fd-megamenu--desktop__section--hover"] &gt; [class="fd-megamenu--desktop__section-button\ fd-megamenu--desktop__section-link\a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ "]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/tools/') and equals(@text,'Tools &amp; calculators')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Tools &amp; calculators"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/tools/</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Tools &amp; calculators</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
</WebElementEntity>