<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d1d757d3-e5b6-4007-a43c-20c8c4a42273</elementGuidId>
    <imagePath></imagePath>
    <name>link_RRSPTips</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="flex-column\ background-padding\ col-12\ col-lg-4\ \ \ \ \ "]:nth-child(2) [class="fd-standard-card--regular\ fd-standard-card--link\ fd-standard-card--clickable\ fd-standard-manual\ fd-mb-32\ fd-card-row--3"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/insights/articles/rrsp_tips/') and equals(@text,'Six tips to make the most of your RRSP')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Six tips to make the most of"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/insights/articles/rrsp_tips/</value>
        <webElementGuid>774e5fa4-210b-463c-8026-f250d5f4657f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Six tips to make the most of your RRSP</value>
        <webElementGuid>774e5fa4-210b-463c-8026-f250d5f4657f</webElementGuid>
    </webElementProperties>
</WebElementEntity>