<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>51b24473-5927-4d3b-a329-c5fc42ef1fd9</elementGuidId>
    <imagePath></imagePath>
    <name>button_viewAllGoals</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]/div[2]/div[4]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="${button_viewAllGoals_class}"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'go to retirement page') and equals(@href,'/en/investor-education/investing-goals/retirement/') and equals(@text,'View all')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[title="go to retirement page"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/investor-education/investing-goals/retirement/</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>View all</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>go to retirement page</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
</WebElementEntity>