<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c94517a7-0f19-49e9-abdf-a5d721f174b0</elementGuidId>
    <imagePath></imagePath>
    <name>investingForBeginnersLink</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/div[3]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fd-megamenu--desktop__content"]:nth-child(3) [class="fd-megamenu--desktop__subject"]:nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/investor-education/investing-beginners/') and equals(@text,'Investing for beginners
            
            We’ll help you understand the basics of investing.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Investing for beginners We’ll"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/investor-education/investing-beginners/</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Investing for beginners
        
        We’ll help you understand the basics of investing.</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
</WebElementEntity>