<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3a0a6319-4701-4181-9b4d-d435b5cb0de0</elementGuidId>
    <imagePath></imagePath>
    <name>link_ETFsOverview</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/div[2]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fd-megamenu--desktop__content"]:nth-child(2) [class="fd-megamenu--desktop__subject"]:nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/investments/etfs/') and equals(@text,'ETFs
            
            Look at our mix of exchange-traded funds (ETFs) for various investment goals, even if you’re just starting to invest.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="ETFs Look at our mix of"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/investments/etfs/</value>
        <webElementGuid>774e5fa4-210b-463c-8026-f250d5f4657f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>ETFs
        
        Look at our mix of exchange-traded funds (ETFs) for various investment goals, even if you’re just starting to invest.</value>
        <webElementGuid>774e5fa4-210b-463c-8026-f250d5f4657f</webElementGuid>
    </webElementProperties>
</WebElementEntity>