<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>783f44a1-0a9f-4e26-9ad9-473279e8e24d</elementGuidId>
    <imagePath></imagePath>
    <name>closeDialogButton2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/md-dialog[1]/md-toolbar[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="md-icon-button\ focus-class\ md-button\ md-focused"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value></value>
        <webElementGuid>ea581d8a-0537-4ce3-a991-71b24b2070b8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>ea581d8a-0537-4ce3-a991-71b24b2070b8</webElementGuid>
    </webElementProperties>
</WebElementEntity>