<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>af3cf13d-1313-4dcb-99e7-340ad61c2a46</elementGuidId>
    <imagePath></imagePath>
    <name>input_fidelityBalancedClass</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/md-dialog[1]/md-dialog-content[1]/md-content[1]/div[5]/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>tbody:nth-child(1) [type="checkbox"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Fidelity Balanced Class"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>a2f6a89e-1a61-41a6-993a-a647a8c94318</webElementGuid>
    </webElementProperties>
</WebElementEntity>