<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8dd8fb49-5213-424d-92fc-58f8f259cb23</elementGuidId>
    <imagePath></imagePath>
    <name>input_allocationPercentage</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/app[1]/ui-view[1]/investor-profile[1]/div[2]/div[2]/div[2]/table[1]/tbody[1]/tr[1]/td[3]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="input-fund-percent\ percent-input\ ng-pristine\ ng-untouched\ ng-valid\ ng-not-empty\ ng-valid-maxlength"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="allocation percentage"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>a2f6a89e-1a61-41a6-993a-a647a8c94318</webElementGuid>
    </webElementProperties>
</WebElementEntity>