<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0d7ac113-d5c0-42de-a40e-0cd427b07c70</elementGuidId>
    <imagePath></imagePath>
    <name>monthlyPreTaxCashFlow</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/app[1]/ui-view[1]/investor-profile[1]/div[1]/form[1]/div[2]/label[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for="monthly-cash-flow"] &gt; [class="custom-radio-button"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>form[name="\$ctrl\.tswpInvestorProfileForm"] span &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>