<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3be00353-178e-4c27-8874-7a52ba0467a1</elementGuidId>
    <imagePath></imagePath>
    <name>link_fidelity_emerging_markets_fund</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/p[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="d-flex\ flex-column\ col-12\ col-sm-12\ col-md-4\ col-lg-4\ col-xl-4\ \ \ "]:nth-child(2) a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Visit the Best Emerging Markets Equity Fund') and equals(@href,'/en/products/funds/ep/?series=F') and equals(@text,'Fidelity Emerging Markets Fund')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Fidelity Emerging Markets Fund"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/products/funds/ep/?series=F</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Fidelity Emerging Markets Fund</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Visit the Best Emerging Markets Equity Fund</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
</WebElementEntity>