<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>949783f3-8c52-41c1-a35a-1b144373f59d</elementGuidId>
    <imagePath></imagePath>
    <name>sendEmailButton</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[8]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="standard-icon-card--button\ fd-common-btn\ fd-primary-btn"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Send an email to Fidelity Customer Service.') and equals(@text,'Send an email')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button &gt;&gt; nth=3</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Send an email</value>
        <webElementGuid>50c3fe0c-bf62-4efc-9b57-c3942c7bfedf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Send an email to Fidelity Customer Service.</value>
        <webElementGuid>50c3fe0c-bf62-4efc-9b57-c3942c7bfedf</webElementGuid>
    </webElementProperties>
</WebElementEntity>