<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3660879b-fe72-46ba-9f72-f80a61c23945</elementGuidId>
    <imagePath></imagePath>
    <name>link_retirementIncomeOptions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[9]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="flex-column\ background-padding\ col-12\ col-lg-3\ \ \ \ \ "]:nth-child(1) &gt; [class="fd-gds-component\ fd-common-card"]:nth-child(1) &gt; [class="fd-standard-card--regular\ fd-standard-card--link\ fd-standard-card--clickable\ fd-standard-manual\ fd-mb-32\ fd-card-row--4"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/insights/articles/retirementincome/') and equals(@text,'Retirement income options')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Retirement income options"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/insights/articles/retirementincome/</value>
        <webElementGuid>7a57bac6-5cf5-4753-9011-30930c1974ce</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Retirement income options</value>
        <webElementGuid>7a57bac6-5cf5-4753-9011-30930c1974ce</webElementGuid>
    </webElementProperties>
</WebElementEntity>