<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5052c86b-4043-4afb-919d-5220065794e2</elementGuidId>
    <imagePath></imagePath>
    <name>link_insights</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="bread-crumb--box"]:nth-child(2) [class="fil-button\ fil-button--textlink\ fil-button--with-icon\ fd-common-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/insights/') and equals(@text,'Insights')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Insights"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/insights/</value>
        <webElementGuid>7a57bac6-5cf5-4753-9011-30930c1974ce</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Insights</value>
        <webElementGuid>7a57bac6-5cf5-4753-9011-30930c1974ce</webElementGuid>
    </webElementProperties>
</WebElementEntity>