<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a7b3efeb-a4e8-4e3f-b2d3-7a349f2b4263</elementGuidId>
    <imagePath></imagePath>
    <name>div_MutualFunds</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/ff-app[1]/div[1]/ff-inputs[1]/div[1]/form[1]/div[1]/div[2]/md-checkbox[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product-selection\ first-option\ ng-pristine\ ng-untouched\ ng-valid\ ng-empty"] &gt; [class="md-container\ md-ink-ripple"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Mutual Funds"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>