<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bb0ecae1-4311-4c4c-98fd-7453ef55bace</elementGuidId>
    <imagePath></imagePath>
    <name>link_GlobalInvestmentNetwork</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fd-gds-component\ fd-common-card"]:nth-child(3) &gt; [class="standard-icon-card\ fd-mb-32\ "]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Global investment network
            
            Fidelity's global organization has extensive resources and expertise with a disciplined investment process.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Global investment network Fidelity's global organization has extensive"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Global investment network
        
        Fidelity's global organization has extensive resources and expertise with a disciplined investment process.</value>
        <webElementGuid>63327e27-e6a4-4e9b-af9c-dc7aac5c3b4d</webElementGuid>
    </webElementProperties>
</WebElementEntity>