<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f33f3a9a-29ce-44fc-8d11-882d7c667bdc</elementGuidId>
    <imagePath></imagePath>
    <name>md_backdrop</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/md-backdrop[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="md-select-backdrop\ md-click-catcher\ ng-scope"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>md-backdrop</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>