<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b92c1c2f-b7bc-411e-ad8a-836a12ef5d34</elementGuidId>
    <imagePath></imagePath>
    <name>md_ManagedPortfolios</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/ff-app[1]/div[1]/ff-inputs[1]/div[1]/form[1]/div[1]/div[2]/md-checkbox[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product-selection\ middle-option\ ng-pristine\ ng-untouched\ ng-valid\ ng-not-empty\ md-checked"]:nth-child(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Managed Portfolios"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>deef9c7a-44b6-47a4-a2d1-3f7be67def7c</webElementGuid>
    </webElementProperties>
</WebElementEntity>