<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dbe273ff-5b47-4293-a6c7-7f0e0dde148c</elementGuidId>
    <imagePath></imagePath>
    <name>md_PrivateInvestmentPools2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/ff-app[1]/div[1]/ff-inputs[1]/div[1]/form[1]/div[1]/div[2]/md-checkbox[5]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product-selection\ last-option\ ng-valid\ ng-dirty\ ng-valid-parse\ ng-touched\ ng-empty"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Private Investment Pools"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>a2f6a89e-1a61-41a6-993a-a647a8c94318</webElementGuid>
    </webElementProperties>
</WebElementEntity>