<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5f45706d-91d2-4d77-aeb3-73a3d8fb6805</elementGuidId>
    <imagePath></imagePath>
    <name>link_language</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[1]/div[1]/nav[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li &gt; [class="fd-icons--header\ fd-icons--header__lang"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'view our website in Français') and equals(@href,'/fr/products/etfs/fbal/?language=fr') and equals(@text,'Français')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Français"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/fr/products/etfs/fbal/?language=fr</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Français</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>view our website in Français</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
</WebElementEntity>