<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2755f514-d18f-487a-bf73-47a22c00474d</elementGuidId>
    <imagePath></imagePath>
    <name>option_series_b</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#bs-select-2-1</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'bs-select-2-1') and equals(@text,'Series B')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#bs-select-2-1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>bs-select-2-1</value>
        <webElementGuid>86ff7c32-aad1-4b36-b36c-efe219fdf365</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Series B</value>
        <webElementGuid>86ff7c32-aad1-4b36-b36c-efe219fdf365</webElementGuid>
    </webElementProperties>
</WebElementEntity>