<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>289de453-74ef-4659-82e9-13649e297fcc</elementGuidId>
    <imagePath></imagePath>
    <name>fidelityCanadaSustainabilityLink</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/footer[1]/div[1]/div[1]/div[3]/div[1]/ul[1]/li[1]/ul[1]/li[11]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-child(11) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/aboutus/sustainability/') and equals(@text,'Fidelity Canada Sustainability')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>li:nth-child(11) &gt; a</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/aboutus/sustainability/</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Fidelity Canada Sustainability</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
</WebElementEntity>