<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>74eee2ac-342d-407a-b069-6ea8dddf5037</elementGuidId>
    <imagePath></imagePath>
    <name>link_view_fund_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[1]/td[57]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>["[class=\"dropdown-menu\\ show\"] &gt; [class=\"dropdown-item\"]:nth-child(1)"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/products/funds/abe/?code=2143')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:role=link[name=\"View Fund\"i]"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/products/funds/abe/?code=2143</value>
        <webElementGuid>86ff7c32-aad1-4b36-b36c-efe219fdf365</webElementGuid>
    </webElementProperties>
</WebElementEntity>