<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4212648b-bf84-4299-9213-20e9fae5b5e1</elementGuidId>
    <imagePath></imagePath>
    <name>option_my_watch_list</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#bs-select-1-0</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'bs-select-1-0') and equals(@text,'My watch list')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#bs-select-1-0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>bs-select-1-0</value>
        <webElementGuid>6fcceb1f-84a2-489e-ba24-12a7049369fa</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>My watch list</value>
        <webElementGuid>6fcceb1f-84a2-489e-ba24-12a7049369fa</webElementGuid>
    </webElementProperties>
</WebElementEntity>