<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5e132203-d9a3-4810-95a6-68028370e4a8</elementGuidId>
    <imagePath></imagePath>
    <name>checkbox_clearpath_retirement_portfolios2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/ff-app[1]/div[1]/ff-inputs[1]/div[1]/form[1]/div[1]/div[2]/md-checkbox[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product-selection\ middle-option\ ng-valid\ ng-dirty\ ng-valid-parse\ ng-touched\ ng-empty"]:nth-child(4)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="ClearPath Retirement"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>6fcceb1f-84a2-489e-ba24-12a7049369fa</webElementGuid>
    </webElementProperties>
</WebElementEntity>