<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cbed9c92-b3e0-43fe-a2f4-d331ab99d8e8</elementGuidId>
    <imagePath></imagePath>
    <name>div_PrivateInvestmentPools5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/ff-app[1]/div[1]/ff-inputs[1]/div[1]/form[1]/div[1]/div[2]/md-checkbox[5]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product-selection\ last-option\ ng-pristine\ ng-untouched\ ng-valid\ ng-empty"] &gt; [class="md-container\ md-ink-ripple"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Private Investment Pools"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>