<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d4db86e5-43fa-46ca-8fdb-59f3a70ca9c2</elementGuidId>
    <imagePath></imagePath>
    <name>div_MutualFunds2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/ff-app[1]/div[1]/ff-inputs[1]/div[1]/form[1]/div[1]/div[2]/md-checkbox[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product-selection\ first-option\ ng-untouched\ ng-valid\ md-checked\ ng-not-empty\ ng-dirty\ ng-valid-parse"] &gt; [class="md-container\ md-ink-ripple"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Mutual Funds"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>