<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ab9f6dd3-a85a-464f-871e-8a012243fa48</elementGuidId>
    <imagePath></imagePath>
    <name>div_ManagedPortfolios</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/ff-app[1]/div[1]/ff-inputs[1]/div[1]/form[1]/div[1]/div[2]/md-checkbox[3]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product-selection\ middle-option\ ng-pristine\ ng-untouched\ ng-valid\ ng-empty"]:nth-child(3) &gt; [class="md-container\ md-ink-ripple"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Managed Portfolios"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>