<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>af91b09b-8a08-4274-9e4b-b0c62cdb7999</elementGuidId>
    <imagePath></imagePath>
    <name>div_ETFs4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/ff-app[1]/div[1]/ff-inputs[1]/div[1]/form[1]/div[1]/div[2]/md-checkbox[2]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product-selection\ middle-option\ ng-untouched\ ng-valid\ ng-dirty\ ng-valid-parse\ md-checked\ ng-not-empty"] &gt; [class="md-container\ md-ink-ripple"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="ETFs"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>