<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1a22e919-1caf-458f-8f8e-59265402fe54</elementGuidId>
    <imagePath></imagePath>
    <name>fidelityAdvantageBitcoinETFFundOption</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/md-virtual-repeat-container[1]/div[1]/div[2]/ul[1]/li[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#ul-52 &gt; [role="option"]:nth-child(2)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#ul-52 &gt;&gt; internal:role=option &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>