<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>93be4dd0-70f9-4535-bbce-2d32177255f2</elementGuidId>
    <imagePath></imagePath>
    <name>item_InvestmentListItem</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/md-virtual-repeat-container[1]/div[1]/div[2]/ul[1]/li[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#ul-52 &gt; [class="ng-scope"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#ul-52 &gt;&gt; internal:role=listitem</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>