<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>68b5cd42-93c0-4136-8aa3-f2373fe5c235</elementGuidId>
    <imagePath></imagePath>
    <name>link_add_to_watchlist</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/ff-app[1]/div[1]/ff-results[1]/div[1]/div[2]/div[2]/ff-overview[1]/div[2]/table[1]/tbody[1]/tr[1]/td[2]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-scope"]:nth-child(1) [class="watch-button\ ng-scope\ ng-isolate-scope"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'javascript:void(0);')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="add to watchlist"i &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>javascript:void(0);</value>
        <webElementGuid>6fcceb1f-84a2-489e-ba24-12a7049369fa</webElementGuid>
    </webElementProperties>
</WebElementEntity>