<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>efeea5ea-e276-45c2-bf81-0c8c70ad77c3</elementGuidId>
    <imagePath></imagePath>
    <name>span_object2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/ff-app[1]/div[1]/ff-inputs[1]/div[1]/form[1]/div[3]/div[1]/div[2]/custom-select[1]/md-input-container[1]/md-select[1]/md-select-value[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#select_value_label_6 &gt; span:nth-child(1)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#select_value_label_6 span &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>