<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>249270df-1899-44c7-876d-77df7751b985</elementGuidId>
    <imagePath></imagePath>
    <name>combobox_all_sales_options</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ dropdown-toggle\ bs-placeholder\ btn-light"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'All sales options') and equals(@type,'button') and equals(@text,'All sales options')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=combobox[name="All sales options"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>All sales options</value>
        <webElementGuid>6fcceb1f-84a2-489e-ba24-12a7049369fa</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>All sales options</value>
        <webElementGuid>6fcceb1f-84a2-489e-ba24-12a7049369fa</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>6fcceb1f-84a2-489e-ba24-12a7049369fa</webElementGuid>
    </webElementProperties>
</WebElementEntity>