<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4ecd9ed6-c987-4e35-988c-3b14d80bd8e4</elementGuidId>
    <imagePath></imagePath>
    <name>linkOptionB</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/div[1]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fd-col-ticker\ text-center\ px-0\ mt-2\ mr-1\ mb-1"]:nth-child(2) &gt; #fund-fact-dl</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'fund-fact-dl') and equals(@title,'fund facts for series B of fund Canadian Asset Allocation') and equals(@href,'/content/dam/fidelity/en/documents/fund-facts/caa/FF_CAA_B_en.pdf')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(2) &gt; #fund-fact-dl</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/content/dam/fidelity/en/documents/fund-facts/caa/FF_CAA_B_en.pdf</value>
        <webElementGuid>ea581d8a-0537-4ce3-a991-71b24b2070b8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>fund-fact-dl</value>
        <webElementGuid>ea581d8a-0537-4ce3-a991-71b24b2070b8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>fund facts for series B of fund Canadian Asset Allocation</value>
        <webElementGuid>ea581d8a-0537-4ce3-a991-71b24b2070b8</webElementGuid>
    </webElementProperties>
</WebElementEntity>