<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c9ea9a46-a8fa-4e3c-be1e-b229b679ff80</elementGuidId>
    <imagePath></imagePath>
    <name>link_SearchByFund</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fd-feature-info--btn2\ fd-feature-info--btn--without-image"] &gt; [class="fd-common-btn\ fd-primary-btn"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Search by fund name, fund code, ticker') and equals(@href,'/en/priceandperformance/') and equals(@text,'Search by fund name, fund code, ticker')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Search by fund name, fund"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/priceandperformance/</value>
        <webElementGuid>deef9c7a-44b6-47a4-a2d1-3f7be67def7c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Search by fund name, fund code, ticker</value>
        <webElementGuid>deef9c7a-44b6-47a4-a2d1-3f7be67def7c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Search by fund name, fund code, ticker</value>
        <webElementGuid>deef9c7a-44b6-47a4-a2d1-3f7be67def7c</webElementGuid>
    </webElementProperties>
</WebElementEntity>