<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>396491b3-2a82-466c-985a-4892bc522d6e</elementGuidId>
    <imagePath></imagePath>
    <name>link_AwardsOverview</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/insights/awards/') and equals(@text,'Awards
            
            At Fidelity, we believe better research drives long-term performance.
            
            See all awards')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/insights/awards/</value>
        <webElementGuid>6fcceb1f-84a2-489e-ba24-12a7049369fa</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Awards
        
        At Fidelity, we believe better research drives long-term performance.
        
        See all awards</value>
        <webElementGuid>6fcceb1f-84a2-489e-ba24-12a7049369fa</webElementGuid>
    </webElementProperties>
</WebElementEntity>