<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b17b4896-5159-4f3a-89c1-fed250e8c232</elementGuidId>
    <imagePath></imagePath>
    <name>div_InsightsArticles</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>