<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>61f91896-8bcf-4dea-9cda-9d26109cd2e6</elementGuidId>
    <imagePath></imagePath>
    <name>div_InsightsArticles</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>