<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d11fc2c9-5566-49bb-8b47-9af4631bc411</elementGuidId>
    <imagePath></imagePath>
    <name>link_RRSPs101Chinese</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[1]/div[3]/article[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fd-editorial-card--regular\ flex-fill\ "]:nth-child(3) &gt; [class="fd-editorial-card--link\a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ fd-editorial-card--media-pdf"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/content/dam/fidelity/en/documents/other-pdfs/brochure_rrsp_101_c.pdf') and equals(@text,'RRSPs 101
            
            (Chinese version)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="RRSPs 101 → (Chinese version)"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/content/dam/fidelity/en/documents/other-pdfs/brochure_rrsp_101_c.pdf</value>
        <webElementGuid>774e5fa4-210b-463c-8026-f250d5f4657f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>RRSPs 101
        
        (Chinese version)</value>
        <webElementGuid>774e5fa4-210b-463c-8026-f250d5f4657f</webElementGuid>
    </webElementProperties>
</WebElementEntity>