<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1fe30f7e-2ed3-43ad-8f96-608e7dd00f1a</elementGuidId>
    <imagePath></imagePath>
    <name>button_navigationActions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/main[1]/section[2]/div[1]/div[1]/div[2]/div[4]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="${button_navigationActions_class}"] &gt; [class="btn\ next-btn\ next-btn-en\ active"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Next')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#question-${button_navigationActions_question} &gt;&gt; internal:role=button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Next</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
</WebElementEntity>