<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9c434fd6-9197-474f-8795-c5b6c0d1c7db</elementGuidId>
    <imagePath></imagePath>
    <name>button_navigationOption</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/main[1]/section[2]/div[1]/div[1]/div[2]/div[4]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="${button_navigationOption_class}"] &gt; [class="btn\ next-btn\ next-btn-en\ active"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Next')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#question-${button_navigationOption_question} &gt;&gt; internal:role=button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Next</value>
        <webElementGuid>0bdbbb3c-549d-47c3-b23f-99a344489dca</webElementGuid>
    </webElementProperties>
</WebElementEntity>