<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ee0b02c7-4f29-4b16-a060-fc1aa60357c0</elementGuidId>
    <imagePath></imagePath>
    <name>link_fidelity_connects_live_webcasts</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fd-standard-card--regular\ fd-standard-card--link\ fd-standard-card--clickable\ fd-standard-manual\ fd-mb-32\ fd-card-row--2\ fd-locks"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/external-redirects/fidelityconnects-multi-reg/') and equals(@text,'FidelityConnects: Live webcasts for financial advisors
            
            Get frequent and direct access to advisor-focused insights on trending issues that affect you and your clients.
            
            Advisors register now')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="FidelityConnects: Live"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/external-redirects/fidelityconnects-multi-reg/</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>FidelityConnects: Live webcasts for financial advisors
        
        Get frequent and direct access to advisor-focused insights on trending issues that affect you and your clients.
        
        Advisors register now</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
</WebElementEntity>