<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>aee35825-9859-4b1c-8179-8fa7e62b2b13</elementGuidId>
    <imagePath></imagePath>
    <name>body_Object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fidca"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>body</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>