<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ad119079-d2ac-4ecd-a4c2-cc831e4949e2</elementGuidId>
    <imagePath></imagePath>
    <name>div_object3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/main[1]/section[2]/div[1]/div[4]/div[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="main-content\ mar-b-dbl"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="4 of 5 How much have you"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>