<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2f4db9bc-c0df-4775-87ab-6ea5f1a28b4c</elementGuidId>
    <imagePath></imagePath>
    <name>div_object6</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/main[1]/section[4]/div[2]/div[5]/div[3]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="dividers"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.dividers</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>