<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7ff91590-e5b8-4120-ae97-a0e048855026</elementGuidId>
    <imagePath></imagePath>
    <name>startOverButton</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/main[1]/div[6]/div[1]/a[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ back-btn"]:nth-child(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'javascript:void(0);') and equals(@text,'Start over')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.nav-buttons &gt; a:nth-child(3)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>javascript:void(0);</value>
        <webElementGuid>0bdbbb3c-549d-47c3-b23f-99a344489dca</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Start over</value>
        <webElementGuid>0bdbbb3c-549d-47c3-b23f-99a344489dca</webElementGuid>
    </webElementProperties>
</WebElementEntity>