<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e28ed9ce-f267-4646-ad26-af17b07f64d0</elementGuidId>
    <imagePath></imagePath>
    <name>button_clearAllFilters</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/details[1]/summary[1]/div[1]/button[29]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="filter-clear"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Clear all filters')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Clear all filters"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Clear all filters</value>
        <webElementGuid>7a57bac6-5cf5-4753-9011-30930c1974ce</webElementGuid>
    </webElementProperties>
</WebElementEntity>