<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c6d64630-cf75-41ae-a56d-ae233c552716</elementGuidId>
    <imagePath></imagePath>
    <name>link_editorial_card</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="col-12\ col-lg-4\ filter-card\ filter-card--init"]:nth-child(1) [class="editorial-card\ clickable\ editorial-card-top\ fd-mb-0\ fd-locks"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/insights/videos/exploring-fixed-income/') and equals(@text,'FidelityConnects: Exploring fixed income 
            Join Institutional Portfolio Manager Beau Coash as he shares his views on today’s fixed income markets and what clients should be keeping a close eye on as we enter 2025.
            Beau Coash
            Institutional Portfolio Manager
            December 05, 2024')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="video-player FidelityConnects: Exploring fixed income Join Institutional"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/insights/videos/exploring-fixed-income/</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>FidelityConnects: Exploring fixed income 
        Join Institutional Portfolio Manager Beau Coash as he shares his views on today’s fixed income markets and what clients should be keeping a close eye on as we enter 2025.
        Beau Coash
        Institutional Portfolio Manager
        December 05, 2024</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
</WebElementEntity>