<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c2ce15d7-5529-4891-8c1f-0ea255189000</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>