<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>344918cf-07d4-45a7-aa7a-d8180287947c</elementGuidId>
    <imagePath></imagePath>
    <name>fundsDropdown</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/section[1]/article[1]/div[1]/section[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ dropdown-toggle\ btn-light"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Funds') and equals(@type,'button') and equals(@text,'Funds')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#container-main section button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Funds</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Funds</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
</WebElementEntity>