<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>560254f2-62db-413f-8227-7c6cc1697bd4</elementGuidId>
    <imagePath></imagePath>
    <name>fundNameInput</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/md-dialog[1]/md-dialog-content[1]/md-content[1]/md-input-container[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#input_0</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'input_0') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Fund name or code"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>input_0</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
</WebElementEntity>