<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>853e290e-67ce-4f77-89ca-00470733da3c</elementGuidId>
    <imagePath></imagePath>
    <name>fundNameInput23</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/md-dialog[1]/md-dialog-content[1]/md-content[1]/md-input-container[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#input_2</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'input_2') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Fund name or code"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>input_2</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
</WebElementEntity>