<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b570a4b8-4a6a-4f5f-ba8f-496e72632a3d</elementGuidId>
    <imagePath></imagePath>
    <name>input_employment_and_other_income</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/section[1]/form[1]/div[2]/div[1]/div[1]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#employmentIncome</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'employmentIncome') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Employment and other income"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>employmentIncome</value>
        <webElementGuid>6fcceb1f-84a2-489e-ba24-12a7049369fa</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>6fcceb1f-84a2-489e-ba24-12a7049369fa</webElementGuid>
    </webElementProperties>
</WebElementEntity>