<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5cf569d9-439a-454d-bfbd-17f71e989859</elementGuidId>
    <imagePath></imagePath>
    <name>link_years</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[3]/div[1]/article[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="d-flex\ flex-column\ col-12\ col-sm-4\ col-md-4\ col-lg-4\ \ \ "]:nth-child(1) [class="fd-editorial-card--link\a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ "]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/investor-education/ditching-debt/') and equals(@text,'5 ways to ditch debt and better manage your money')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="5 ways to ditch debt and"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/investor-education/ditching-debt/</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>5 ways to ditch debt and better manage your money</value>
        <webElementGuid>96845374-342c-495e-bd7d-ab96461fdae0</webElementGuid>
    </webElementProperties>
</WebElementEntity>