<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7f9b9e59-160b-4b4c-a7bb-56e882b959ef</elementGuidId>
    <imagePath></imagePath>
    <name>rrspContributionsInput</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/section[1]/form[1]/div[3]/div[1]/div[2]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#rrspContribution</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'rrspContribution') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="RRSP contributions"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>rrspContribution</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>d1407254-4af5-4997-8f67-29f958844523</webElementGuid>
    </webElementProperties>
</WebElementEntity>