<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>718d28b3-9403-462c-b7f9-a1a180f8f68a</elementGuidId>
    <imagePath></imagePath>
    <name>link_toolsAndCalculators</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/div[1]/div[1]/menu[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fd-megamenu--desktop__section\ fd-megamenu--desktop__section--hover"] &gt; [class="fd-megamenu--desktop__section-button\ fd-megamenu--desktop__section-link\a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ "]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/tools/') and equals(@text,'Tools &amp; calculators')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>menu &gt;&gt; internal:role=link &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/tools/</value>
        <webElementGuid>a2f6a89e-1a61-41a6-993a-a647a8c94318</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Tools &amp; calculators</value>
        <webElementGuid>a2f6a89e-1a61-41a6-993a-a647a8c94318</webElementGuid>
    </webElementProperties>
</WebElementEntity>